# Generated by Django 5.2.13 on 2026-06-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_file',
        ),
    ]
