# Generated by Django 5.2.13 on 2026-06-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads_app', '0002_initial'),
        ('users_auth_app', '0002_remove_customuser_profile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='uploads_app.fileupload'),
        ),
    ]
