# Generated by Django 5.2.13 on 2026-06-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0004_customuser_created_at_customuser_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_file',
            new_name='file',
        ),
    ]
